package view;

import controller.App;
import java.awt.Frame;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;
import model.HashTable;
import model.Summary;

/**
 * Let the user choose authors
 *
 * @author Arístides Pérez
 */
public class AuthorsView extends javax.swing.JFrame {

    private final Menu menuGUI;
    private final HashTable<String, LinkedList<Summary>> authorsTable;
    private final DefaultListModel<String> authorsModel = new DefaultListModel<>();

    /**
     * Creates new form Help
     *
     * @param menuGUI menu user interface
     * @param authorsTable author-summaries pair HashTable
     */
    public AuthorsView(Menu menuGUI, HashTable authorsTable) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.menuGUI = menuGUI;
        this.authorsTable = authorsTable;

        // Summaries View Initialization
        Object[] authors = App.getAuthors().keysToArray();
        for (var author : authors) {
            authorsModel.addElement(author.toString());
        }
        authorsList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        authorsList.setSelectedIndex(0);

        this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();
        titleBar = new javax.swing.JPanel();
        exitButton = new javax.swing.JLabel();
        minimizeButton = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        icon = new javax.swing.JLabel();
        scrollAuthors = new javax.swing.JScrollPane();
        authorsList = new javax.swing.JList<>();
        selectButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        Main.setBackground(new java.awt.Color(255, 255, 255));
        Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleBar.setBackground(new java.awt.Color(255, 255, 255));

        exitButton.setFont(new java.awt.Font("sansserif", 0, 22)); // NOI18N
        exitButton.setForeground(new java.awt.Color(51, 51, 51));
        exitButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitButton.setText("X");
        exitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
        });

        minimizeButton.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        minimizeButton.setForeground(new java.awt.Color(51, 51, 51));
        minimizeButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizeButton.setText("-");
        minimizeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout titleBarLayout = new javax.swing.GroupLayout(titleBar);
        titleBar.setLayout(titleBarLayout);
        titleBarLayout.setHorizontalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleBarLayout.createSequentialGroup()
                .addContainerGap(246, Short.MAX_VALUE)
                .addComponent(minimizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        titleBarLayout.setVerticalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleBarLayout.createSequentialGroup()
                .addGroup(titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minimizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Main.add(titleBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 40));

        backButton.setBackground(new java.awt.Color(0, 51, 153));
        backButton.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Volver");
        backButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        Main.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 80, 30));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/icon.png"))); // NOI18N
        Main.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        authorsList.setModel(authorsModel);
        scrollAuthors.setViewportView(authorsList);

        Main.add(scrollAuthors, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 260, 200));

        selectButton.setBackground(new java.awt.Color(0, 51, 153));
        selectButton.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        selectButton.setForeground(new java.awt.Color(255, 255, 255));
        selectButton.setText("Seleccionar");
        selectButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        selectButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButtonActionPerformed(evt);
            }
        });
        Main.add(selectButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 160, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        this.setVisible(false);
        this.dispose();
        menuGUI.setVisible(true);
    }//GEN-LAST:event_exitButtonMouseClicked

    private void minimizeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeButtonMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minimizeButtonMouseClicked

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
        this.dispose();
        menuGUI.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void selectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButtonActionPerformed
        String selectedAuthor = authorsList.getSelectedValue();
        this.setVisible(false);
        this.dispose();
        SelectSummary analysisGUI = new SelectSummary(menuGUI, App.getSummaries(), selectedAuthor, 1);
    }//GEN-LAST:event_selectButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Main;
    private javax.swing.JList<String> authorsList;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel exitButton;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel minimizeButton;
    private javax.swing.JScrollPane scrollAuthors;
    private javax.swing.JButton selectButton;
    private javax.swing.JPanel titleBar;
    // End of variables declaration//GEN-END:variables
}
