package view;

import java.awt.Frame;

/**
 * Shows a Summary Analysis
 *
 * @author Arístides Pérez
 */
public class SummaryAnalysis extends javax.swing.JFrame {
    private final Menu menuGUI;

    /**
     * Creates new form Analysis
     *
     * @param menuGUI menu user interface
     */
    public SummaryAnalysis(Menu menuGUI, String analysis) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.menuGUI = menuGUI;
        textInfo.setText(analysis);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();
        titleBar = new javax.swing.JPanel();
        exitButton = new javax.swing.JLabel();
        minimizeButton = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        icon = new javax.swing.JLabel();
        scrollText = new javax.swing.JScrollPane();
        textInfo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        Main.setBackground(new java.awt.Color(255, 255, 255));
        Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleBar.setBackground(new java.awt.Color(255, 255, 255));

        exitButton.setFont(new java.awt.Font("sansserif", 0, 22)); // NOI18N
        exitButton.setForeground(new java.awt.Color(51, 51, 51));
        exitButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitButton.setText("X");
        exitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
        });

        minimizeButton.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        minimizeButton.setForeground(new java.awt.Color(51, 51, 51));
        minimizeButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizeButton.setText("-");
        minimizeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout titleBarLayout = new javax.swing.GroupLayout(titleBar);
        titleBar.setLayout(titleBarLayout);
        titleBarLayout.setHorizontalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleBarLayout.createSequentialGroup()
                .addContainerGap(506, Short.MAX_VALUE)
                .addComponent(minimizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        titleBarLayout.setVerticalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleBarLayout.createSequentialGroup()
                .addGroup(titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minimizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Main.add(titleBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 40));

        backButton.setBackground(new java.awt.Color(0, 51, 153));
        backButton.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Volver al Menú");
        backButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        Main.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 180, 30));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/icon.png"))); // NOI18N
        Main.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        scrollText.setBorder(null);
        scrollText.setFocusable(false);

        textInfo.setEditable(false);
        textInfo.setBackground(new java.awt.Color(255, 255, 255));
        textInfo.setColumns(20);
        textInfo.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N
        textInfo.setForeground(new java.awt.Color(51, 51, 51));
        textInfo.setLineWrap(true);
        textInfo.setRows(5);
        textInfo.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. In elementum facilisis justo sed dictum. Duis mattis, libero vitae semper hendrerit, magna nunc aliquam tortor, sed sagittis massa orci eu lectus. Cras a scelerisque est. Suspendisse porta varius iaculis. Donec ac malesuada est. Vivamus sit amet volutpat ante. Etiam eleifend eros eu metus viverra, eu lacinia neque pharetra. Aliquam sed nulla id orci efficitur tempus ut in justo.\nDonec eu dui et ipsum egestas aliquet quis sit amet nunc. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla tincidunt risus ac finibus faucibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget blandit massa. Curabitur porta, diam nec lacinia interdum, arcu risus lobortis tellus, ac commodo purus nisi at ipsum. Nullam non nunc ut felis laoreet laoreet ut id leo.");
        textInfo.setWrapStyleWord(true);
        textInfo.setBorder(null);
        scrollText.setViewportView(textInfo);

        Main.add(scrollText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 480, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        this.setVisible(false);
        this.dispose();
        menuGUI.setVisible(true);
    }//GEN-LAST:event_exitButtonMouseClicked

    private void minimizeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeButtonMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minimizeButtonMouseClicked

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
        this.dispose();
        menuGUI.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Main;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel exitButton;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel minimizeButton;
    private javax.swing.JScrollPane scrollText;
    private javax.swing.JTextArea textInfo;
    private javax.swing.JPanel titleBar;
    // End of variables declaration//GEN-END:variables
}
